### ISSUE TITLE
About PMPage problem

### ISSUE THREAD

**Issue by Brent-bai** [xarial/xcad#101]
I encountered the following issues when using the PMPage interface: 1 The custom wpf interface only displays a portion in the property manager page; 2. Can a label be added on the same line before the text box to identify the content to be filled in this text box; 3. It seems that the webview2 control cannot be used for wpf in the class library, and the display is a blank page

**Comment by Brent-bai** [comment]
How do I chage the size of the user control wpf view (the yellow box is the true size)  which in a pmp page.
![control](https://github.com/xarial/xcad/assets/71217629/ef2c7cf6-3279-46f8-aeb5-7aaf0509f3d3)

**Comment by Brent-bai** [comment]
I chage a method: add the Mgrtab. 
`private void CreatFeatureMgrTab()
        {
            var doc = Application.Documents.Active;
            if (doc == null)
            { return; }
            // prp_m_page.Show(prp_m_model);
            if (tab == null)
            {
                tab = CreateFeatureManagerTab<prpFeatureMgrControl>(doc);
                
                tab.Control.Sw = Application.Sw;
            }
            else
            {
                tab.Close();
                tab.Dispose();
                tab = null;
            }

        }`
It also does not work well, when I click the tab, it only display part view of the tab:
![tab](https://github.com/xarial/xcad/assets/71217629/4e6b8069-bd46-4d01-a1e3-d14c94091649)
So i need adjust the size of whole tab.

**Comment by artem1t** [comment]
> How do I chage the size of the user control wpf view (the yellow box is the true size) which in a pmp page. ![control](https://user-images.githubusercontent.com/71217629/252257733-ef2c7cf6-3279-46f8-aeb5-7aaf0509f3d3.png)

You can use [ControlOptionsAttribute](https://github.com/xarial/xcad/blob/master/src/Base/UI/PropertyPage/Attributes/ControlOptionsAttribute.cs#L27)

**Comment by Brent-bai** [comment]
Thanks you very much! It worked.
