### ISSUE TITLE
PropertyManagerPage Icon arrange problem

### ISSUE THREAD

**Issue by Brent-bai** [xarial/xcad#115]
Can the icon buttons be arranged horizontally, as shown in the figure：
![icon_arr](https://github.com/xarial/xcad/assets/71217629/1a44d613-9589-4bcc-b10f-227feb9fa549)

**Comment by artem1t** [comment]
Yes, it can be arranged this way. Check [this example](https://github.com/xarial/xcad-examples/tree/master/PMPageToggleBitmapButtons)

**Comment by Brent-bai** [comment]
Thank you very much. It worked, but have some issues. The icons arrange with different distance, and some icons' position are fixed, some of them are folat.
