### ISSUE TITLE
How to Register Icons for Customization?

### ISSUE THREAD

**Issue by foreachthing** [xarial/xcad#130]
If I want to customize a certain toolbar, I cannot access the icons (commands) from my addin (swTools4):
<img width="475" alt="image" src="https://github.com/xarial/xcad/assets/10420187/45d4391b-2291-4145-bbb1-9b94ea9b4b3c">
No icons (commands) listed. Even though my toolbar (and menu) are full with commands.

Please compare to "Surface":
<img width="475" alt="image" src="https://github.com/xarial/xcad/assets/10420187/016529be-deb5-42a2-a1e0-4f64c44f5f3b">
All possible commands are available.

Any help is appreciated.

**Comment by andrMollo** [comment]
Hi there,
I reached out to @artem1t some time ago: it seems there is a bug in SolidWorks, the icons are actually there they are just tiny. You can try to mouse over and see if the tooltip is displayed.

I hope it helps.

**Comment by foreachthing** [comment]
@andrMollo, yes, it does help - but not. 😦 
I don't undestand why this is a SolidWorks-Bug ... since when I made my toolbar without xcad, it worked as expected. Any example project I've found, using xcad, does not show the icons. So, I'll leave this issue open as it only happens when using xcad.

**Comment by artem1t** [comment]
@foreachthing, you are correct. I have just done a test and it is indeed displayed correctly with vanilla SOLIDWORKS API, @andrMollo, I apologize as I was mistaken. xCAD is still using the vanilla API (e.g. calling the same Command Manager API) but something breaks this particular icon rendering, perhaps image encoding or something like that. I will be working on this now as I have a working example with SW API so can compare where it is breaking.

**Comment by foreachthing** [comment]
Sweet!!!
![image](https://github.com/xarial/xcad/assets/10420187/64fc06b7-7ee2-4d97-9075-29475b744e39)

Thanks for your hard work!! 😀

**Comment by artem1t** [comment]
Fixed in dev build. The issue was related to disposing of temp icons. Icons were removed immediately after the toolbar is created which has caused this issue. Now the icons are removed when the group is removed.

**Comment by foreachthing** [comment]
Yeah, thanks! I saw that and tried to compile it.
Still trying to find out how to compile without all the examples :roll_eyes:

**Comment by andrMollo** [comment]
Yesss! Thanks a lot!

**Comment by andrMollo** [comment]
Hi @artem1t , I'm using `xCAD` as a NuGet package (`v0.8`). Any chance that this fix will be released there as well?
