### ISSUE TITLE
Updating Combobox based on another comboBox selection change

### ISSUE THREAD

**Issue by emersonbottero** [xarial/xcad#5]
this code works great.

` public override IEnumerable<string> ProvideItems(SwApplication app) => Directory.GetDirectories(@"X:/"); `

but how can I show in the next combobox the subfolders of the selected folder in the previous combobox?

![image](https://user-images.githubusercontent.com/12377432/89093111-d70ca100-d38d-11ea-8ac1-3cda21180c1a.png)

**Comment by artem1t** [comment]
I think it needs to be implemented similarly to [control dependencies](https://xcad.xarial.com/property-pages/controls/dependencies/), e.t. ProvideItems should also pass dependent controls and be called every time dependency changed.

**Comment by artem1t** [comment]
This is now implemented an available in [preview builds](https://xcad.xarial.com/installation/preview-builds/), will be later merged in release

**Comment by artem1t** [comment]
Merged to release
